/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Heranca;

import java.util.Date;



public class App {
    public static void main(String[] args) {
       Vendedor vendedor = new Vendedor();
       Motorista motorista = new Motorista();
       
       
       
       vendedor.setNome("AAAA");
       vendedor.setSalario(100.0f);
       vendedor.setCpf("12332532");
       vendedor.setDataNascimento(new Date());
       vendedor.setComissaoPorItem(10.0f);
       vendedor.setComissaoPorItem(10);
       
       System.out.println("O vendedor tal tem o salario de :" + vendedor.calcularSalario());
       
    
       
     
    }
}
